import React from "react";
import { motion } from "framer-motion";
import { ArrowRight, Check, ChevronDown, ChevronRight, LockKeyhole, Menu, ShieldCheck, Sparkles, WalletCards, X } from "lucide-react";
import { useTheme } from "../context/ThemeContext";

interface LandingPageProps { onLogin: () => void; onAdminPortalClick: () => void; }

const features = [
  ["Secure Payment Handling", "Our platform ensures that all transactions are processed through a trusted and secure payment system.", "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=500&q=80"],
  ["Easy Dispute Resolution", "When disagreements arise, our platform offers a fair and transparent dispute resolution process.", "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=500&q=80"],
  ["Real Time Notification", "Stay informed at every stage of your transaction with real-time notifications and clear updates.", "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=500&q=80"],
  ["Multicurrency Support", "Our platform supports transactions in multiple currencies, making it accessible for users worldwide.", "https://images.unsplash.com/photo-1559526324-593bc073d938?auto=format&fit=crop&w=500&q=80"],
];
const faqs = ["What is an ESCROW service?", "How does your ESCROW service work?", "Who owns the ESCROW service?", "Is my personal and financial information safe?", "What payment methods do you accept?"];
const partners = ["EARTH2.0", "treva.", "zoo tv", "acme", "idea", "FOX HUB"];

export default function LandingPage({ onLogin, onAdminPortalClick }: LandingPageProps) {
  const { theme, toggleTheme } = useTheme();
  const [menuOpen, setMenuOpen] = React.useState(false);
  const [openFaq, setOpenFaq] = React.useState<number | null>(null);
  const goTo = (id: string) => { setMenuOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); };

  return <div className="landing-page min-h-screen overflow-x-hidden bg-white text-[#182d50]">
    <header className="landing-nav mx-auto flex max-w-[1180px] items-center justify-between px-5 py-5 sm:px-8">
      <button className="flex items-center gap-2" onClick={() => goTo("top")} aria-label="Poly-Crow home"><img src="/logo.png" alt="Poly-Crow" className="h-9 w-9 object-contain" /><span className="text-[15px] font-extrabold tracking-[-0.04em]">POLY<span className="text-[#14a94b]">-CROW</span></span></button>
      <nav className="hidden items-center gap-8 text-[11px] font-semibold md:flex"><button onClick={() => goTo("top")} className="text-[#14a94b]">Home</button><button onClick={() => goTo("benefits")} className="hover:text-[#14a94b]">About</button><button onClick={() => goTo("blogs")} className="hover:text-[#14a94b]">Blogs</button><button onClick={() => goTo("footer")} className="hover:text-[#14a94b]">Contact</button></nav>
      <div className="flex items-center gap-2"><button onClick={toggleTheme} className="hidden text-[10px] font-bold text-[#63718a] sm:block" aria-label="Toggle theme">{theme === "dark" ? "LIGHT" : "DARK"}</button><button onClick={onLogin} className="landing-pill landing-pill-small">Account <ArrowRight size={12} /></button><button onClick={() => setMenuOpen(!menuOpen)} className="p-2 md:hidden" aria-label="Toggle menu">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></div>
      {menuOpen && <div className="absolute left-5 right-5 top-16 z-30 flex flex-col gap-0 border border-[#dce8df] bg-white p-3 shadow-lg md:hidden">{[["top", "Home"], ["benefits", "About"], ["blogs", "Blogs"], ["footer", "Contact"]].map(([id, label]) => <button key={id} onClick={() => goTo(id)} className="py-1.5 text-left text-sm font-semibold">{label}</button>)}<button onClick={onLogin} className="landing-pill mt-2 py-2 text-sm">Open account</button></div>}
    </header>

    <main id="top">
      <section className="mx-auto grid max-w-[1180px] items-center gap-12 px-5 pb-16 pt-12 sm:px-8 lg:grid-cols-[1fr_0.85fr] lg:pb-24 lg:pt-20"><motion.div initial={{ opacity: 0, x: -24 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.6 }}><p className="mb-5 text-[10px] font-bold uppercase tracking-[0.25em] text-[#14a94b]">The trusted escrow platform</p><h1 className="max-w-[620px] text-5xl font-display font-semibold leading-[0.98] tracking-[-0.06em] sm:text-7xl">SECURE EVERY <span className="text-[#14a94b]">DEAL</span> WITH CONFIDENCE</h1><p className="mt-7 max-w-lg text-sm leading-7 text-[#718097]">Experience secure transactions with EscrowLab. We protect your money, build trust, and make every deal simple.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={onLogin} className="landing-pill px-6 py-3">Start Escrowing <ArrowRight size={15} /></button><button onClick={() => goTo("features")} className="landing-outline px-6 py-3">How it works <ChevronRight size={15} /></button></div><div className="mt-10 flex gap-7 text-[9px] font-semibold text-[#8090a6]"><span><strong className="block text-lg text-[#14a94b]">20,000+</strong>Total Transactions</span><span><strong className="block text-lg text-[#14a94b]">120+</strong>Countries</span><span><strong className="block text-lg text-[#14a94b]">4.8/5</strong>Active Users</span></div></motion.div><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7, delay: 0.1 }} className="relative min-h-[330px]"><div className="absolute inset-8 rounded-[45%] bg-[#31c761] lg:inset-5" /><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=85" alt="People completing a trusted business deal" className="absolute inset-5 h-[310px] w-[calc(100%-40px)] rounded-[28px] object-cover mix-blend-multiply opacity-80" /><div className="landing-form-card absolute right-0 top-5 w-[min(92%,330px)] p-5 sm:right-2"><div className="mb-3 flex gap-2"><div className="h-9 flex-1 border border-[#dce4e2] p-2 text-[9px] text-[#6e7c90]">I'm Selling</div><div className="h-9 flex-1 border border-[#dce4e2] p-2 text-[9px] text-[#6e7c90]">Select Category⌄</div></div><input className="mb-3 h-12 w-full border border-[#dce4e2] px-3 text-[9px] outline-none" placeholder="Do you require a position or custom service?" /><div className="mb-4 flex h-10 border border-[#dce4e2] text-[9px]"><span className="border-r border-[#dce4e2] p-3">For</span><input className="min-w-0 flex-1 px-3 outline-none" placeholder="Enter amount" /><span className="p-3">USD</span></div><button onClick={onLogin} className="landing-pill w-full py-3 text-[10px]">Start Escrowing</button></div></motion.div></section>
      <div className="mx-auto flex max-w-[1060px] flex-wrap items-center justify-between gap-5 px-5 pb-20 text-xl font-bold text-[#9ca7b5] opacity-80 grayscale sm:px-8">{partners.map((partner) => <span key={partner}>{partner}</span>)}</div>

      <section id="benefits" className="mx-auto grid max-w-[1180px] items-center gap-12 px-5 py-16 sm:px-8 lg:grid-cols-2"><div><h2 className="text-4xl font-display font-semibold leading-[1.05] tracking-[-0.05em]">BENEFITS OF <span className="text-[#14a94b]">ESCROWLAB</span></h2><p className="mt-3 text-xs text-[#718097]">Experience our seamless, hassle-free transactions.</p><div className="mt-7 space-y-4">{["Dispute Prevention", "Enhanced Flexibility", "Simplified Transactions", "Reduce Risk"].map((item) => <div key={item} className="flex gap-3"><Check className="mt-0.5 text-[#14a94b]" size={15} /><div><strong className="text-xs">{item}</strong><p className="mt-1 text-[10px] leading-4 text-[#8490a0]">Our platform protects your payment and gives you peace of mind.</p></div></div>)}</div><button onClick={onLogin} className="landing-pill mt-7 px-5 py-2 text-[10px]">Let's get started <ArrowRight size={13} /></button></div><div className="grid grid-cols-2 gap-3"><img src="https://images.unsplash.com/photo-1521791055366-0d553872125f?auto=format&fit=crop&w=700&q=80" alt="Business partners shaking hands" className="col-span-2 h-40 w-full rounded-2xl object-cover" /><img src="https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=500&q=80" alt="Team reviewing a contract" className="h-32 w-full rounded-2xl object-cover" /><img src="https://images.unsplash.com/photo-1551836022-4c4c79ecde51?auto=format&fit=crop&w=500&q=80" alt="Woman using a phone at work" className="h-32 w-full rounded-2xl object-cover" /></div></section>

      <section id="features" className="mx-auto max-w-[1180px] px-5 py-16 sm:px-8"><h2 className="mb-9 text-4xl font-display font-semibold tracking-[-0.05em]">OUR <span className="text-[#14a94b]">FEATURES</span></h2><div className="divide-y divide-[#dbe3e1]">{features.map(([title, text, image]) => <div key={title} className="grid items-center gap-5 py-4 sm:grid-cols-[70px_1fr_38px]"><img src={image} alt="" className="h-14 w-14 rounded-xl object-cover" /><div><h3 className="text-sm font-bold">{title}</h3><p className="mt-1 max-w-2xl text-[10px] leading-4 text-[#8490a0]">{text}</p></div><div className="hidden h-6 w-6 items-center justify-center rounded-full border border-[#182d50] sm:flex"><Check size={13} /></div></div>)}</div></section>

      <section id="how-it-works" className="bg-[#f4f7f6] px-5 py-14 sm:px-8"><div className="mx-auto max-w-[1180px]"><h2 className="mb-9 text-3xl font-display font-semibold tracking-[-0.05em]">HOW ESCROW <span className="text-[#14a94b]">WORKS</span></h2><div className="grid gap-2 md:grid-cols-4">{[["Step 1", "AGREEMENT", "Both parties agree on transaction terms."], ["Step 2", "SUBMIT PAYMENT", "The buyer deposits the agreed payment."], ["Step 3", "DELIVER", "The seller delivers the agreed item."], ["Step 4", "RELEASE PAYMENT", "Funds are released after confirmation."]].map(([step, title, text], index) => <div key={step} className="relative border border-[#aebbb8] bg-white p-6 text-center shadow-sm"><div className={`absolute -top-5 left-1/2 flex h-10 w-10 -translate-x-1/2 items-center justify-center rounded-full border-2 border-[#14a94b] bg-white text-[#14a94b] ${index === 3 ? "border-[#1b278d] text-[#1b278d]" : ""}`}><WalletCards size={17} /></div><p className="mt-4 text-[8px] text-[#8490a0]">{step}</p><h3 className="mt-3 text-[10px] font-bold text-[#14a94b]">{title}</h3><p className="mt-3 text-[9px] leading-4 text-[#8490a0]">{text}</p></div>)}</div></div></section>

      <section id="security" className="mx-auto grid max-w-[1050px] items-center gap-10 px-5 py-20 sm:px-8 lg:grid-cols-2"><div className="overflow-hidden rounded-3xl bg-[#e7f9ee] p-4"><img src="https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=850&q=80" alt="Secure digital payment technology" className="h-64 w-full rounded-2xl object-cover" /></div><div><h2 className="text-3xl font-display font-semibold tracking-[-0.05em]">ADVANCED <span className="text-[#14a94b]">SECURITY FEATURES</span></h2><p className="mt-2 text-xs text-[#718097]">Protecting your transactions with cutting-edge technology.</p><div className="mt-6 space-y-4">{[["End-to-End Encryption", LockKeyhole], ["Two-Factor Authentication", ShieldCheck], ["Fraud Detection", Sparkles]].map(([label, Icon]) => <div key={label as string} className="flex gap-3"><Icon size={17} className="text-[#14a94b]" /><div><strong className="text-xs">{label as string}</strong><p className="mt-1 text-[10px] text-[#8490a0]">Advanced protection keeps every transaction safe.</p></div></div>)}</div><button onClick={onLogin} className="landing-pill mt-6 px-5 py-2 text-[10px]">Let's get started <ArrowRight size={13} /></button></div></section>

      <section id="blogs" className="mx-auto max-w-[1180px] px-5 py-16 sm:px-8"><div className="mb-8 flex items-center justify-between"><h2 className="text-3xl font-display font-semibold">OUR <span className="text-[#14a94b]">BLOGS</span></h2><button className="landing-outline px-3 py-1 text-[9px]">View All <ArrowRight size={12} /></button></div><div className="grid gap-4 md:grid-cols-3">{["https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=600&q=80", "https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=600&q=80", "https://images.unsplash.com/photo-1551836022-3b4c1c4c8e56?auto=format&fit=crop&w=600&q=80"].map((image, index) => <article key={image} className="border border-[#e1e8e5] p-2"><img src={image} alt="" className="h-32 w-full object-cover" /><p className="mt-3 text-[9px] font-bold text-[#14a94b]">0{index + 6} JULY 2025</p><h3 className="mt-2 text-sm font-bold">{["What if there is a disagreement?", "Payment Procession: Mass...", "What is an Escrow Agreement?"][index]}</h3><p className="mt-2 text-[10px] leading-4 text-[#8490a0]">Learn more about safe and seamless escrow transactions.</p></article>)}</div></section>

      <section className="mx-auto grid max-w-[1050px] gap-8 px-5 py-12 sm:px-8 lg:grid-cols-[0.55fr_1fr]"><div><h2 className="text-3xl font-display font-semibold text-[#14a94b]">FAQS</h2><p className="mt-2 text-xs text-[#718097]">Get quick answers to our most commonly asked questions.</p><button onClick={onLogin} className="landing-pill mt-5 px-5 py-2 text-[10px]">Contact <ArrowRight size={13} /></button></div><div className="border-t border-[#dce5e1]">{faqs.map((faq, index) => <div key={faq} className="border-b border-[#dce5e1]"><button onClick={() => setOpenFaq(openFaq === index ? null : index)} className="flex w-full items-center justify-between py-4 text-left text-[10px] font-bold">{faq}<ChevronDown size={14} className={openFaq === index ? "rotate-180 text-[#14a94b]" : ""} /></button>{openFaq === index && <p className="pb-4 text-[10px] leading-5 text-[#8490a0]">EscrowLab protects both parties by holding funds securely until the agreed conditions are met.</p>}</div>)}</div></section>
    </main>

    <footer id="footer" className="bg-[#08722d] px-5 pb-8 pt-12 text-white sm:px-8"><div className="mx-auto grid max-w-[1180px] gap-10 md:grid-cols-[1.2fr_0.8fr_0.8fr_0.8fr]"><div><div className="flex items-center gap-2"><img src="/logo.png" alt="EscrowLab" className="h-8 w-8 brightness-0 invert" /><strong>ESCROW<span className="text-[#6ee69a]">LAB</span></strong></div><p className="mt-4 max-w-xs text-[10px] leading-5 text-white/70">Secure and seamless escrow transactions for everyone, everywhere.</p></div>{[["QUICK LINKS", "Home", "About", "Blogs", "Contact"], ["COMPANY", "Terms & Conditions", "Privacy Policy", "Payment Policy", "Company Rules"], ["CONTACT US", "+1 555 434 658", "hello@escrowlab.com", "24/7 Support"]].map(([title, ...links]) => <div key={title}><h3 className="mb-4 text-[10px] font-bold tracking-widest text-[#6ee69a]">{title}</h3><div className="space-y-2 text-[10px] text-white/70">{links.map((link) => <p key={link}>{link}</p>)}</div></div>)}</div><div className="mx-auto mt-10 max-w-[1180px] border-t border-white/20 pt-5 text-center text-[9px] text-white/60">Copyright © 2025 EscrowLab. All rights reserved. <button onClick={onAdminPortalClick} className="ml-2 underline">Admin Portal</button></div></footer>
  </div>;
}